# 开发环境默认的profile，其他环境需要指定启动参数，比如：java -jar log-monitor.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev

#服务监控用
server:
  port: -1
management:
  port: 64003
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
          
---
# 开发环境配置
spring:
  profiles: dev
zookeeper:
  host1: 127.0.0.1:2181

#---
## 测试环境配置
#spring:
#  profiles: test
#zookeeper:
#  host1: 192.168.0.42:2181
#  host2: 192.168.0.42:2182
#  host3: 192.168.0.42:2183
#mongo:
#  host: 192.168.0.23:27017
#rabbitmq:
#  host: 192.168.0.44
#  username: ysb
#  password: rabbitYsb
#---
## 生产环境配置
#spring:
#  profiles: prod
#zookeeper:
#  host1: 192.168.0.33:2181
#  host2: 192.168.0.34:2181
#  host3: 192.168.0.38:2181
#mongo:
#  host: 192.168.0.48:27017
#rabbitmq:
#  host: 192.168.0.51
#  username: ysb
#  password: rabbitYsb